apiVersion: "v2"
appVersion: "latest"
name: "common-res"
type: "application"
version: "1.0.7"
deprecated: false
description: "Helm chart with common resources"
home: https://helm-repo-public.luminarinfra.com
keywords:
  - common-res
kubeVersion: ">=1.20.0-0"
sources:
  - https://github.com/luminartech/helm-charts-public
maintainers:
  - name: "Luminar SRE Team"
    email: "sre@luminartech.com"
  - name: "Satish Gaikwad"
    email: "satish.gaikwad@luminartech.com"
  - name: "Hennadii Mykhailiuta"
    email: "hennadii.mykhailiuta@luminartech.com"
dependencies:
  - name: "common-gitops"
    version: "1.0.4"
    repository: "https://helm-repo-public.luminarinfra.com/"
