annotations:
  category: Infrastructure
apiVersion: v2
# App version follows crossplane AWS provider version
appVersion: "0.34.0"
description: A Helm chart for crossplane AWS IAM resources
# Naming pattern: crossplane-aws-<AWS_SERVICENAME>
# Note: This chart name is used to extract the aws service name as common-gitops.names.aws.service variable
# AWS service name must match with the actual lowercase service names used in the crossplane aws provider CRDs
name: crossplane-aws-iam
# Below version must match the app version for the consistency.
# Update minor bit if new tag is needed. e.g. 0.29.0-1
version: "0.34.0-1"
home: https://helm-repo-public.luminarinfra.com
sources:
  - https://github.com/luminartech/helm-charts-public/charts/crossplane-aws-iam
maintainers:
  - name: SRE
    email: sre@luminartech.com
  - name: Satish Gaikwad
    email: satish.gaikwad@luminartech.com
  - name: Hennadii Mykhailiuta
    email: hennadii.mykhailiuta@luminartech.com
dependencies:
  - name: common-gitops
    version: "1.0.7"
    # repository: file://../../shared/common-gitops
    repository: https://helm-repo-public.luminarinfra.com/
