{{- $kind := "Job" -}}
{{- $root := . -}}
{{- $kindObj := or (get $root.Values $kind) (dict) -}}
{{- range $name, $item := $kindObj.items -}}
  {{- if hasKey $item "enabled" | ternary ($item.enabled) (ne $kindObj.enabled false) }}
---
apiVersion: batch/v1
kind: {{ $kind }}
metadata:
  name: {{ include "common-gitops.names.itemFullname" (dict "root" $root "name" $name "override" .name) }}
    {{- include "common-gitops.labels" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
    {{- include "common-gitops.annotations" (dict "root" $root "name" $name "kind" $kind) | trim | nindent 2 }}
spec:
    {{- with .backoffLimit }}
  backoffLimit: {{ . }}
    {{- end -}}
    {{- with .podSpec }}
  template:
      {{- include "common-res.podSpec" (dict "root" $root "name" $name "kind" $kind) | nindent 4 }}
    {{- end -}}
  {{- end -}}
{{- end }}
